package com.mancera.eulerproj.problem0002;

/*
 Each new term in the Fibonacci sequence is generated by adding
 the previous two terms. By starting with 1 and 2, the first 10 terms will be:

          1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

  By considering the terms in the Fibonacci sequence whose values 
  do not exceed four million, find the sum of the even-valued terms.
 */
public class Main {

	public static void main(String[] args) {
		
		//since we already know that 2 is even and we start from 2
		int sum = 2;
		//we start the iteration from 2
		int current = 2;
		//need to keep reference to previous to add in each iteration
		int previous = 1;
		
		while(current < 4000000) {
			int temp = current;
			current += previous;
			previous = temp;
			
			//add only even ones
			if(current % 2 == 0) {
				sum += current;
			}
		}
		
		System.out.println("Sum: " + sum);
	}
	
}
